/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.example.domainmodel.domainmodel.DomainmodelFactory
 * @model kind="package"
 * @generated
 */
public interface DomainmodelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "domainmodel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/domainmodel/Domainmodel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "domainmodel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DomainmodelPackage eINSTANCE = org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl.init();

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.ModelImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECLARATIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.DeclarationImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Conditionandaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__CONDITIONANDACTION = 0;

  /**
   * The feature id for the '<em><b>Story</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__STORY = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.ConditionandActionImpl <em>Conditionand Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.ConditionandActionImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getConditionandAction()
   * @generated
   */
  int CONDITIONAND_ACTION = 2;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAND_ACTION__CONDITIONS = 0;

  /**
   * The number of structural features of the '<em>Conditionand Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAND_ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.StoryImpl <em>Story</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.StoryImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getStory()
   * @generated
   */
  int STORY = 3;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__REACTION = 0;

  /**
   * The number of structural features of the '<em>Story</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.ShipImpl <em>Ship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.ShipImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getShip()
   * @generated
   */
  int SHIP = 4;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIP__REACTION = STORY__REACTION;

  /**
   * The feature id for the '<em><b>Item</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIP__ITEM = STORY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Address</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIP__ADDRESS = STORY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIP_FEATURE_COUNT = STORY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.OrdermaterialsImpl <em>Ordermaterials</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.OrdermaterialsImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getOrdermaterials()
   * @generated
   */
  int ORDERMATERIALS = 5;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDERMATERIALS__REACTION = STORY__REACTION;

  /**
   * The feature id for the '<em><b>Material</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDERMATERIALS__MATERIAL = STORY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ordermaterials</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDERMATERIALS_FEATURE_COUNT = STORY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.QueryitemsImpl <em>Queryitems</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.QueryitemsImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getQueryitems()
   * @generated
   */
  int QUERYITEMS = 6;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERYITEMS__REACTION = STORY__REACTION;

  /**
   * The feature id for the '<em><b>Item</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERYITEMS__ITEM = STORY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Queryitems</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERYITEMS_FEATURE_COUNT = STORY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.ItemImpl <em>Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.ItemImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getItem()
   * @generated
   */
  int ITEM = 7;

  /**
   * The feature id for the '<em><b>Item</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__ITEM = 0;

  /**
   * The number of structural features of the '<em>Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.AddressImpl <em>Address</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.AddressImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getAddress()
   * @generated
   */
  int ADDRESS = 8;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDRESS__ADDRESS = 0;

  /**
   * The number of structural features of the '<em>Address</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDRESS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.MaterialImpl <em>Material</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.MaterialImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getMaterial()
   * @generated
   */
  int MATERIAL = 9;

  /**
   * The feature id for the '<em><b>Material</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATERIAL__MATERIAL = 0;

  /**
   * The number of structural features of the '<em>Material</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATERIAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.ConditionImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 10;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION = 0;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.domainmodel.domainmodel.impl.ReactionImpl <em>Reaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.domainmodel.domainmodel.impl.ReactionImpl
   * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getReaction()
   * @generated
   */
  int REACTION = 11;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REACTION__REACTION = 0;

  /**
   * The number of structural features of the '<em>Reaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REACTION_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.example.domainmodel.domainmodel.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.domainmodel.domainmodel.Model#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see org.example.domainmodel.domainmodel.Model#getDeclarations()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Declarations();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.example.domainmodel.domainmodel.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link org.example.domainmodel.domainmodel.Declaration#getConditionandaction <em>Conditionandaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditionandaction</em>'.
   * @see org.example.domainmodel.domainmodel.Declaration#getConditionandaction()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Conditionandaction();

  /**
   * Returns the meta object for the containment reference '{@link org.example.domainmodel.domainmodel.Declaration#getStory <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Story</em>'.
   * @see org.example.domainmodel.domainmodel.Declaration#getStory()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Story();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.ConditionandAction <em>Conditionand Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditionand Action</em>'.
   * @see org.example.domainmodel.domainmodel.ConditionandAction
   * @generated
   */
  EClass getConditionandAction();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.domainmodel.domainmodel.ConditionandAction#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see org.example.domainmodel.domainmodel.ConditionandAction#getConditions()
   * @see #getConditionandAction()
   * @generated
   */
  EReference getConditionandAction_Conditions();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Story <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Story</em>'.
   * @see org.example.domainmodel.domainmodel.Story
   * @generated
   */
  EClass getStory();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.domainmodel.domainmodel.Story#getReaction <em>Reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Reaction</em>'.
   * @see org.example.domainmodel.domainmodel.Story#getReaction()
   * @see #getStory()
   * @generated
   */
  EReference getStory_Reaction();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Ship <em>Ship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ship</em>'.
   * @see org.example.domainmodel.domainmodel.Ship
   * @generated
   */
  EClass getShip();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.domainmodel.domainmodel.Ship#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Item</em>'.
   * @see org.example.domainmodel.domainmodel.Ship#getItem()
   * @see #getShip()
   * @generated
   */
  EReference getShip_Item();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.domainmodel.domainmodel.Ship#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Address</em>'.
   * @see org.example.domainmodel.domainmodel.Ship#getAddress()
   * @see #getShip()
   * @generated
   */
  EReference getShip_Address();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Ordermaterials <em>Ordermaterials</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ordermaterials</em>'.
   * @see org.example.domainmodel.domainmodel.Ordermaterials
   * @generated
   */
  EClass getOrdermaterials();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.domainmodel.domainmodel.Ordermaterials#getMaterial <em>Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Material</em>'.
   * @see org.example.domainmodel.domainmodel.Ordermaterials#getMaterial()
   * @see #getOrdermaterials()
   * @generated
   */
  EReference getOrdermaterials_Material();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Queryitems <em>Queryitems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Queryitems</em>'.
   * @see org.example.domainmodel.domainmodel.Queryitems
   * @generated
   */
  EClass getQueryitems();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.domainmodel.domainmodel.Queryitems#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Item</em>'.
   * @see org.example.domainmodel.domainmodel.Queryitems#getItem()
   * @see #getQueryitems()
   * @generated
   */
  EReference getQueryitems_Item();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Item <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item</em>'.
   * @see org.example.domainmodel.domainmodel.Item
   * @generated
   */
  EClass getItem();

  /**
   * Returns the meta object for the attribute '{@link org.example.domainmodel.domainmodel.Item#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Item</em>'.
   * @see org.example.domainmodel.domainmodel.Item#getItem()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_Item();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Address <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Address</em>'.
   * @see org.example.domainmodel.domainmodel.Address
   * @generated
   */
  EClass getAddress();

  /**
   * Returns the meta object for the attribute '{@link org.example.domainmodel.domainmodel.Address#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.example.domainmodel.domainmodel.Address#getAddress()
   * @see #getAddress()
   * @generated
   */
  EAttribute getAddress_Address();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Material <em>Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Material</em>'.
   * @see org.example.domainmodel.domainmodel.Material
   * @generated
   */
  EClass getMaterial();

  /**
   * Returns the meta object for the attribute '{@link org.example.domainmodel.domainmodel.Material#getMaterial <em>Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Material</em>'.
   * @see org.example.domainmodel.domainmodel.Material#getMaterial()
   * @see #getMaterial()
   * @generated
   */
  EAttribute getMaterial_Material();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.example.domainmodel.domainmodel.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link org.example.domainmodel.domainmodel.Condition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.example.domainmodel.domainmodel.Condition#getCondition()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Condition();

  /**
   * Returns the meta object for class '{@link org.example.domainmodel.domainmodel.Reaction <em>Reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reaction</em>'.
   * @see org.example.domainmodel.domainmodel.Reaction
   * @generated
   */
  EClass getReaction();

  /**
   * Returns the meta object for the attribute '{@link org.example.domainmodel.domainmodel.Reaction#getReaction <em>Reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reaction</em>'.
   * @see org.example.domainmodel.domainmodel.Reaction#getReaction()
   * @see #getReaction()
   * @generated
   */
  EAttribute getReaction_Reaction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DomainmodelFactory getDomainmodelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.ModelImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECLARATIONS = eINSTANCE.getModel_Declarations();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.DeclarationImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Conditionandaction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__CONDITIONANDACTION = eINSTANCE.getDeclaration_Conditionandaction();

    /**
     * The meta object literal for the '<em><b>Story</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__STORY = eINSTANCE.getDeclaration_Story();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.ConditionandActionImpl <em>Conditionand Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.ConditionandActionImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getConditionandAction()
     * @generated
     */
    EClass CONDITIONAND_ACTION = eINSTANCE.getConditionandAction();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAND_ACTION__CONDITIONS = eINSTANCE.getConditionandAction_Conditions();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.StoryImpl <em>Story</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.StoryImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getStory()
     * @generated
     */
    EClass STORY = eINSTANCE.getStory();

    /**
     * The meta object literal for the '<em><b>Reaction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY__REACTION = eINSTANCE.getStory_Reaction();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.ShipImpl <em>Ship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.ShipImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getShip()
     * @generated
     */
    EClass SHIP = eINSTANCE.getShip();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHIP__ITEM = eINSTANCE.getShip_Item();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHIP__ADDRESS = eINSTANCE.getShip_Address();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.OrdermaterialsImpl <em>Ordermaterials</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.OrdermaterialsImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getOrdermaterials()
     * @generated
     */
    EClass ORDERMATERIALS = eINSTANCE.getOrdermaterials();

    /**
     * The meta object literal for the '<em><b>Material</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDERMATERIALS__MATERIAL = eINSTANCE.getOrdermaterials_Material();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.QueryitemsImpl <em>Queryitems</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.QueryitemsImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getQueryitems()
     * @generated
     */
    EClass QUERYITEMS = eINSTANCE.getQueryitems();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERYITEMS__ITEM = eINSTANCE.getQueryitems_Item();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.ItemImpl <em>Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.ItemImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getItem()
     * @generated
     */
    EClass ITEM = eINSTANCE.getItem();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__ITEM = eINSTANCE.getItem_Item();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.AddressImpl <em>Address</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.AddressImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getAddress()
     * @generated
     */
    EClass ADDRESS = eINSTANCE.getAddress();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDRESS__ADDRESS = eINSTANCE.getAddress_Address();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.MaterialImpl <em>Material</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.MaterialImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getMaterial()
     * @generated
     */
    EClass MATERIAL = eINSTANCE.getMaterial();

    /**
     * The meta object literal for the '<em><b>Material</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATERIAL__MATERIAL = eINSTANCE.getMaterial_Material();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.ConditionImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__CONDITION = eINSTANCE.getCondition_Condition();

    /**
     * The meta object literal for the '{@link org.example.domainmodel.domainmodel.impl.ReactionImpl <em>Reaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.domainmodel.domainmodel.impl.ReactionImpl
     * @see org.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getReaction()
     * @generated
     */
    EClass REACTION = eINSTANCE.getReaction();

    /**
     * The meta object literal for the '<em><b>Reaction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REACTION__REACTION = eINSTANCE.getReaction_Reaction();

  }

} //DomainmodelPackage
