/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Material</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.domainmodel.Material#getMaterial <em>Material</em>}</li>
 * </ul>
 *
 * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getMaterial()
 * @model
 * @generated
 */
public interface Material extends EObject
{
  /**
   * Returns the value of the '<em><b>Material</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Material</em>' attribute.
   * @see #setMaterial(String)
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getMaterial_Material()
   * @model
   * @generated
   */
  String getMaterial();

  /**
   * Sets the value of the '{@link org.example.domainmodel.domainmodel.Material#getMaterial <em>Material</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Material</em>' attribute.
   * @see #getMaterial()
   * @generated
   */
  void setMaterial(String value);

} // Material
