/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ordermaterials</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.domainmodel.Ordermaterials#getMaterial <em>Material</em>}</li>
 * </ul>
 *
 * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getOrdermaterials()
 * @model
 * @generated
 */
public interface Ordermaterials extends Story
{
  /**
   * Returns the value of the '<em><b>Material</b></em>' containment reference list.
   * The list contents are of type {@link org.example.domainmodel.domainmodel.Material}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Material</em>' containment reference list.
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getOrdermaterials_Material()
   * @model containment="true"
   * @generated
   */
  EList<Material> getMaterial();

} // Ordermaterials
