/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.domainmodel.Reaction#getReaction <em>Reaction</em>}</li>
 * </ul>
 *
 * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getReaction()
 * @model
 * @generated
 */
public interface Reaction extends EObject
{
  /**
   * Returns the value of the '<em><b>Reaction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reaction</em>' attribute.
   * @see #setReaction(String)
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getReaction_Reaction()
   * @model
   * @generated
   */
  String getReaction();

  /**
   * Sets the value of the '{@link org.example.domainmodel.domainmodel.Reaction#getReaction <em>Reaction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reaction</em>' attribute.
   * @see #getReaction()
   * @generated
   */
  void setReaction(String value);

} // Reaction
