/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.domainmodel.Ship#getItem <em>Item</em>}</li>
 *   <li>{@link org.example.domainmodel.domainmodel.Ship#getAddress <em>Address</em>}</li>
 * </ul>
 *
 * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getShip()
 * @model
 * @generated
 */
public interface Ship extends Story
{
  /**
   * Returns the value of the '<em><b>Item</b></em>' containment reference list.
   * The list contents are of type {@link org.example.domainmodel.domainmodel.Item}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item</em>' containment reference list.
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getShip_Item()
   * @model containment="true"
   * @generated
   */
  EList<Item> getItem();

  /**
   * Returns the value of the '<em><b>Address</b></em>' containment reference list.
   * The list contents are of type {@link org.example.domainmodel.domainmodel.Address}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Address</em>' containment reference list.
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getShip_Address()
   * @model containment="true"
   * @generated
   */
  EList<Address> getAddress();

} // Ship
