/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.example.domainmodel.domainmodel.Address;
import org.example.domainmodel.domainmodel.DomainmodelPackage;
import org.example.domainmodel.domainmodel.Item;
import org.example.domainmodel.domainmodel.Ship;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ship</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.domainmodel.impl.ShipImpl#getItem <em>Item</em>}</li>
 *   <li>{@link org.example.domainmodel.domainmodel.impl.ShipImpl#getAddress <em>Address</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ShipImpl extends StoryImpl implements Ship
{
  /**
   * The cached value of the '{@link #getItem() <em>Item</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItem()
   * @generated
   * @ordered
   */
  protected EList<Item> item;

  /**
   * The cached value of the '{@link #getAddress() <em>Address</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAddress()
   * @generated
   * @ordered
   */
  protected EList<Address> address;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ShipImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainmodelPackage.Literals.SHIP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Item> getItem()
  {
    if (item == null)
    {
      item = new EObjectContainmentEList<Item>(Item.class, this, DomainmodelPackage.SHIP__ITEM);
    }
    return item;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Address> getAddress()
  {
    if (address == null)
    {
      address = new EObjectContainmentEList<Address>(Address.class, this, DomainmodelPackage.SHIP__ADDRESS);
    }
    return address;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DomainmodelPackage.SHIP__ITEM:
        return ((InternalEList<?>)getItem()).basicRemove(otherEnd, msgs);
      case DomainmodelPackage.SHIP__ADDRESS:
        return ((InternalEList<?>)getAddress()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DomainmodelPackage.SHIP__ITEM:
        return getItem();
      case DomainmodelPackage.SHIP__ADDRESS:
        return getAddress();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DomainmodelPackage.SHIP__ITEM:
        getItem().clear();
        getItem().addAll((Collection<? extends Item>)newValue);
        return;
      case DomainmodelPackage.SHIP__ADDRESS:
        getAddress().clear();
        getAddress().addAll((Collection<? extends Address>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.SHIP__ITEM:
        getItem().clear();
        return;
      case DomainmodelPackage.SHIP__ADDRESS:
        getAddress().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.SHIP__ITEM:
        return item != null && !item.isEmpty();
      case DomainmodelPackage.SHIP__ADDRESS:
        return address != null && !address.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ShipImpl
